export type Language = 'pt' | 'en';
export type World = 'crystal' | 'ghost';

export const links = {
  x: 'https://x.com/BiyA_YU',
  vgen: 'https://vgen.co/BiyA_YU',
  youtube: 'https://www.youtube.com/@biyaYU',
  livepix: 'https://livepix.gg/biya',
} as const;

export const worlds = {
  pt: {
    crystal: {
      kicker: 'ONDE A LUZ VIRA ARTE',
      titleLead: 'Arte entre luz',
      titleAccent: 'cristal.',
      desc: 'Explore a expressão visual, os personagens e as criações de Biya.',
      caption: 'CRYSTAL / LUZ, COR E TEXTURA',
    },
    ghost: {
      kicker: 'TAMBÉM HÁ BELEZA NA ESCURIDÃO',
      titleLead: 'Formas da',
      titleAccent: 'noite.',
      desc: 'Uma outra atmosfera para explorar sua arte: sombras, formas e contrastes.',
      caption: 'GHOST / CONTRASTE E EXPRESSÃO',
    },
  },
  en: {
    crystal: {
      kicker: 'WHERE LIGHT BECOMES ART',
      titleLead: 'Art through light',
      titleAccent: 'crystal.',
      desc: 'Explore Biya’s visual expression, characters and creative work.',
      caption: 'CRYSTAL / LIGHT, COLOR & TEXTURE',
    },
    ghost: {
      kicker: 'THERE IS BEAUTY IN THE DARK',
      titleLead: 'Shapes of',
      titleAccent: 'the night.',
      desc: 'Another atmosphere for her work: shadows, shapes and contrast.',
      caption: 'GHOST / CONTRAST & EXPRESSION',
    },
  },
} as const;

export const copy = {
  pt: {
    htmlLang: 'pt-BR',
    title: '💎 BIYA — Parallel Worlds ✦',
    description: 'Arte, personagens, streams e os mundos Crystal × Ghost da Biya. 💜👻',
    nav: ['Portal', 'Arquivo', 'Sinal', 'Jogo', 'Biya'],
    concept: 'CRYSTAL × GHOST / PARALLEL WORLDS',
    role: 'BIYA / ARTISTA DIGITAL & VTUBER',
    welcome: 'UM ESPAÇO PARA A ARTE',
    switchLabel: '01 — ALTERAR FREQUÊNCIA',
    explore: 'EXPLORAR O UNIVERSO',
    portfolio: 'VER PORTFÓLIO',
    stageAria: 'Retratos da identidade visual da Biya',
    crystalAlt: 'Personagem de cabelos brancos iridescentes, traje cristalino, com detalhes rosa e lavanda',
    ghostAlt: 'Fantasia sombria da personagem da Biya, em roxo, com caveira e elementos fantasmagóricos',
    archiveChapter: 'CAP.02 / ARQUIVO DE ARTES',
    archiveTitleA: 'Fragmentos da',
    archiveTitleB: 'imaginação.',
    archivePre: 'UMA EXPOSIÇÃO EM MOVIMENTO',
    archiveDesc: 'Uma seleção visual de obras, personagens e estudos criativos. Use as setas, os pontos ou o teclado para explorar.',
    previous: 'Ver arte anterior',
    next: 'Ver próxima arte',
    expand: 'AMPLIAR ↗',
    archiveFooter: 'OBRAS E VISUAIS AUTORIZADOS PARA O SITE',
    rightsShort: 'Direitos autorais e créditos preservados.',
    intermission: 'Arte em muitas formas. Um olhar em cada detalhe.',
    signalChapter: 'CAP.03 / SINAL RECEBIDO',
    signalTitleA: 'NO',
    signalTitleB: 'AR.',
    signalDesc: 'Além do desenho, existem transmissões, jogos e encontros. Registros públicos da Biya em movimento.',
    channel: 'VER NO CANAL ↗',
    gameChapter: 'CAP.04 / PARALLEL PULSE',
    gameTitle: 'PARALLEL PULSE',
    gameDesc: 'Troque entre Crystal e Ghost no momento certo. Colete o que pertence ao seu mundo, mantenha o combo e atravesse as duas frequências.',
    gameHow: 'Espaço, Enter, clique ou toque para trocar de mundo.',
    gameStart: 'INICIAR SINAL',
    gameRetry: 'TENTAR DE NOVO',
    gameScore: 'PONTOS',
    gameCombo: 'COMBO',
    gameBest: 'RECORDE',
    gameCrystal: 'CRYSTAL',
    gameGhost: 'GHOST',
    gameOver: 'SINAL PERDIDO',
    gameReady: 'DUAS FREQUÊNCIAS. UM RITMO.',
    aboutChapter: 'CAP.05 / CONHEÇA A CRIADORA',
    aboutScript: 'Quem está por trás das artes',
    aboutTitleA: 'OI, EU SOU',
    aboutTitleB: 'BIYA.',
    aboutDesc: 'Biya se apresenta publicamente como artista digital e VTuber. Aqui, suas ilustrações, personagens, streams e canais convivem em dois mundos visuais.',
    commissions: 'ARTES E COMISSÕES',
    videos: 'VÍDEOS E LIVES',
    footerTitle: 'ARTE, PERSONAGENS E EXPERIÊNCIAS DE BIYA',
    back: '↑ VOLTAR AO PORTAL',
    policy: 'POLÍTICA DAS ARTES',
    authorized: 'PUBLICAÇÃO E USO DOS MATERIAIS SELECIONADOS AUTORIZADOS PELA BIYA',
    protection: 'SEM AUTORIZAÇÃO: REPOST, DATASET, TREINAMENTO OU GERAÇÃO POR IA',
    easterEgg: 'NÃO INVOCA ELE.',
    easterHint: 'A frequência 666 foi bloqueada com sucesso.',
    close: 'FECHAR',
  },
  en: {
    htmlLang: 'en',
    title: '💎 BIYA — Parallel Worlds ✦',
    description: 'Art, characters, streams and Biya’s Crystal × Ghost worlds. 💜👻',
    nav: ['Portal', 'Archive', 'Signal', 'Game', 'Biya'],
    concept: 'CRYSTAL × GHOST / PARALLEL WORLDS',
    role: 'BIYA / DIGITAL ARTIST & VTUBER',
    welcome: 'A SPACE FOR ART',
    switchLabel: '01 — SWITCH FREQUENCY',
    explore: 'EXPLORE THE UNIVERSE',
    portfolio: 'VIEW PORTFOLIO',
    stageAria: 'Portraits from Biya’s visual identity',
    crystalAlt: 'Iridescent white-haired character in a crystalline outfit with pink and lavender details',
    ghostAlt: 'Dark fantasy version of Biya’s character with a skull and violet ghostly details',
    archiveChapter: 'CH.02 / ART ARCHIVE',
    archiveTitleA: 'Fragments of',
    archiveTitleB: 'imagination.',
    archivePre: 'AN EXHIBITION IN MOTION',
    archiveDesc: 'A visual selection of artworks, characters and creative studies. Use arrows, dots or the keyboard to explore.',
    previous: 'Previous artwork',
    next: 'Next artwork',
    expand: 'EXPAND ↗',
    archiveFooter: 'ARTWORK AND VISUALS AUTHORIZED FOR THE SITE',
    rightsShort: 'Copyright and credits preserved.',
    intermission: 'Art in many forms. Expression in every detail.',
    signalChapter: 'CH.03 / SIGNAL RECEIVED',
    signalTitleA: 'ON',
    signalTitleB: 'AIR.',
    signalDesc: 'Beyond drawing: streams, games and community moments. Public glimpses of Biya in motion.',
    channel: 'WATCH ON CHANNEL ↗',
    gameChapter: 'CH.04 / PARALLEL PULSE',
    gameTitle: 'PARALLEL PULSE',
    gameDesc: 'Shift between Crystal and Ghost at the right moment. Collect what belongs to your world, keep the combo and cross both frequencies.',
    gameHow: 'Space, Enter, click or tap to switch worlds.',
    gameStart: 'START SIGNAL',
    gameRetry: 'TRY AGAIN',
    gameScore: 'SCORE',
    gameCombo: 'COMBO',
    gameBest: 'BEST',
    gameCrystal: 'CRYSTAL',
    gameGhost: 'GHOST',
    gameOver: 'SIGNAL LOST',
    gameReady: 'TWO FREQUENCIES. ONE RHYTHM.',
    aboutChapter: 'CH.05 / MEET THE CREATOR',
    aboutScript: 'The creator behind the art',
    aboutTitleA: 'HI, I’M',
    aboutTitleB: 'BIYA.',
    aboutDesc: 'Biya publicly describes herself as a digital artist and VTuber. Here, her illustrations, characters, streams and channels coexist across two visual worlds.',
    commissions: 'ART & COMMISSIONS',
    videos: 'VIDEOS & STREAMS',
    footerTitle: 'BIYA’S ART, CHARACTERS AND EXPERIENCES',
    back: '↑ BACK TO PORTAL',
    policy: 'ARTWORK POLICY',
    authorized: 'PUBLICATION AND DISPLAY OF SELECTED MATERIALS AUTHORIZED BY BIYA',
    protection: 'NO UNAUTHORIZED REPOST, DATASET, MODEL TRAINING OR GENERATIVE-AI USE',
    easterEgg: 'DON’T SUMMON HIM.',
    easterHint: 'Frequency 666 was successfully blocked.',
    close: 'CLOSE',
  },
} as const;

export const artworks = [
  {
    id: 'work-01', src: '/assets/artwork/character.webp', width: 1536, height: 2048,
    pt: { tag: 'ILUSTRAÇÃO / OC', title: 'Doce Devaneio', desc: 'Cena delicada com rosas, doces e a identidade visual da personagem.', alt: 'Biya em composição rosa com doces e decoração floral' },
    en: { tag: 'ILLUSTRATION / OC', title: 'Sweet Reverie', desc: 'A delicate scene with roses, sweets and the character’s visual identity.', alt: 'Biya in a pink composition with sweets and flowers' },
  },
  {
    id: 'work-02', src: '/assets/artwork/outfits.webp', width: 1700, height: 769,
    pt: { tag: 'FIGURINOS / ALTERNATIVOS', title: 'Muitas Facetas', desc: 'Uma personagem, muitos figurinos. Cinco roupas temáticas.', alt: 'Cinco roupas alternativas da personagem' },
    en: { tag: 'WARDROBE / ALT OUTFITS', title: 'Many Faces', desc: 'One character, many styles. Five themed outfits.', alt: 'Five alternate outfits for the character' },
  },
  {
    id: 'work-03', src: '/assets/avatars/ghost.webp', width: 1700, height: 1160,
    pt: { tag: 'FANTASIA / SOMBRA', title: 'O Outro Lado', desc: 'Contrastes, fantasmas e uma atmosfera violeta mais intensa.', alt: 'Ilustração violeta da personagem com uma caveira' },
    en: { tag: 'DARK / FANTASY', title: 'The Other Side', desc: 'Contrasts, ghostly motifs and a more intense violet atmosphere.', alt: 'Violet illustration of the character with a skull' },
  },
  {
    id: 'work-04', src: '/assets/avatars/crystal.webp', width: 768, height: 1280,
    pt: { tag: 'OC / IRIDESCENTE', title: 'Coração de Cristal', desc: 'Lavanda, azul-gelo, rosa e transparências suaves.', alt: 'Personagem de cabelos claros segurando um cristal' },
    en: { tag: 'OC / IRIDESCENT', title: 'Crystal Heart', desc: 'Lavender, icy blue, pink and soft translucency.', alt: 'Light-haired character holding a crystal' },
  },
  {
    id: 'work-05', src: '/assets/avatars/expressive.webp', width: 1700, height: 1700,
    pt: { tag: 'OC / CHIBI', title: 'Uma Faísca', desc: 'A versão mais expressiva e descontraída da personagem.', alt: 'Ilustração chibi expressiva da personagem' },
    en: { tag: 'OC / CHIBI', title: 'A Little Spark', desc: 'A more expressive and playful view of the character.', alt: 'Expressive chibi illustration of the character' },
  },
  {
    id: 'work-06', src: '/assets/artwork/shot2.jpg', width: 546, height: 546,
    pt: { tag: 'ACERVO / ANTERIOR', title: 'Eco Violeta', desc: 'Obra do acervo anterior, preservando suas cores originais.', alt: 'Retrato violeta com olhos expressivos' },
    en: { tag: 'OLDER WORK / ART', title: 'Violet Echo', desc: 'A piece from the previous archive, with its original colors intact.', alt: 'Violet portrait with expressive eyes' },
  },
] as const;

export const media = [
  { src: '/assets/streams/live1.jpg', label: 'PHASMOPHOBIA', width: 736, height: 414 },
  { src: '/assets/streams/live2.jpg', label: 'ALIEN: ISOLATION', width: 736, height: 414 },
  { src: '/assets/streams/live3.jpg', label: 'A PIOR VTUBER', width: 736, height: 414 },
] as const;
